clear all

Images = {
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/01F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/01F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/01F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/02F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/02F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/02F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/03F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/03F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/03F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/05F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/05F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/05F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/06F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/06F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/06F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/07F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/07F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/07F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/08F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/08F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/08F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/09F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/09F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/09F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/10F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/10F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/10F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/11F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/11F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/11F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/12F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/12F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/12F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/13F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/13F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/13F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/14F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/14F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/14F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/15F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/15F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/15F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/16F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/16F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/16F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/17F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/17F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/17F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/18F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/18F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/18F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/19F_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/19F_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/19F_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/20M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/20M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/20M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/21M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/21M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/21M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/22M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/22M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/22M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/23M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/23M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/23M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/24M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/24M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/24M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/25M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/25M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/25M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/26M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/26M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/26M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/27M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/27M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/27M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/28M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/28M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/28M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/29M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/29M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/29M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/30M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/30M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/30M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/31M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/31M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/31M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/32M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/32M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/32M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/33M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/33M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/33M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/34M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/34M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/34M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/35M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/35M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/35M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/36M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/36M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/36M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/37M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/37M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/37M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/38M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/38M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/38M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/39M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/39M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/39M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/40M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/40M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/40M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/41M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/41M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/41M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/42M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/42M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/42M_N.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/43M_F.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/43M_H.png';
'/home/heffjos/Documents/Work/Pecina/RevisedNeurofeedback/SocialCogImages/FaceImages/43M_N.png';
};

X = 0;
Y = 0;
ImageY = '';
ImageX = '';
sizes = zeros(numel(Images), 2);
IdxX = 1;
IdxY = 1;

for i = 1:numel(Images)
    im = imread(Images{i}, 'png');
    sizes(i, :) = [size(im, 1) size(im, 2)];

    if sizes(i, 1) > Y
        Y = sizes(i, 1);
        ImageY = Images{i};
        IdxX = i;
    end

    if sizes(i, 2) > X
        X = sizes(i, 2);
        ImageX = Images{i};
        idxY = 1;
    end
end

NormalSizes = sizes;
NormalSizes(IdxX, :) = [];
NormalX = max(NormalSizes(:, 2));
NoramlY = max(NormalSizes(:, 1));
means = mean(NormalSizes, 1);
